### ISSUE TITLE
RtlUpperString test hangs on real hardware

### ISSUE THREAD

**Issue by Fisherman166** [Cxbx-Reloaded/xbox_kernel_test_suite#36]
When running the kernel test suite on my Xbox, the RtlUpperString tests hangs. The last thing I see printed in the logfile is "0x013D - RtlUpperString: Tests Starting". A hard reset of the console is required to exit. Cxbx-R does not hang when running this test for some reason. @Luca1991 please take a look as you implemented this test.

Please test all changes on real hardware and on Cxbx-R. Pull request #37 comments out the test to make forward progress.

**Comment by Luca1991** [comment]
Hi @Fisherman166 I test all my contribution on my real xbox before to push, and often on CxBx-R too.

I don't know why your xbox hangs in the RtlUpperString tests, but mine passes the tests without problems O.o

**Comment by Fisherman166** [comment]
Interesting...Let me see if I can add some prints and find exactly where it is hanging for me.

**Comment by Luca1991** [comment]
I'll also re-test it on my xbox soon

**Comment by JayFoxRox** [comment]
This has been disabled now; without any references on GitHub.
What's the state of this?

**Comment by Fisherman166** [comment]
No one has dug into it. I haven't heard from Luca in many months and I haven't had any freetime since May to really do much Test Suite work.

**Comment by PatrickvL** [comment]
Fair enough. I'll try to reach Luca again....

**Comment by Luca1991** [comment]
Hey just saw the GitHub emails! Sorry for being away for so much time, but the truth is that I'm so busy with real life since May (I still have 2 exams to pass in order to get my major degree at university, and I'm very busy helping my father in his job)... I would really love to find some time for the KTS in the near future, but it is quite hard and I can't promise :(
